--- #YAML:1.0
name:               Regexp-Common
version:            2011041802
abstract:           Provide commonly requested regular expressions
author:
    - Abigail <regexp-common@abigail.be>
license:            mit
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
    strict:               0
build_requires:
    ExtUtils::MakeMaker:  0
    strict:               0
requires:
    perl:    5.00473
    strict:  0
    vars:    0
resources:
    repository:  git://github.com/Abigail/Regexp--Common.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:
    - regular expression
    - pattern
test_requires:
    strict:  0
