#!/opt/perl/bin/perl

use 5.010;

use strict;
use warnings;
no  warnings 'syntax';

my $PDF2TXT = "/opt/local/bin/pdftotext";

my $file = shift;

die "Failed to find $file\n" unless $file && -f $file;

my @list = map {/\b([0-9]{4}])$/ ? $1 : ()} `$PDF2TXT $file -`;
   @list = `$PDF2TXT $file -`;

my %zips;
my $postcodes = 0;
foreach (@list) {
    $postcodes ++ if /^Postcodes$/;
    next unless $postcodes >= 2;
    next if /\bBoxes/i;   # Don't trigger on 'PO Boxes'.
    $zips {$1} = 1 if /\s([0-9]{4})$/;
}

@list = sort {$a <=> $b} keys %zips;

say for @list;

__END__
